spring.application.name=ilpCw1Application
# CW1 Spec: Port 8080 is consumed for incoming requests
server.port=8080
management.endpoints.web.exposure.include=health, info, metrics, env, beans, loggers
management.endpoint.health.show-details=always
logging.level.ilp.tutorials.ilp_cw1.service.impl.DroneServiceImpl=DEBUG
